name: git_hub_uchun
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  lottie: ^3.1.3
  carousel_slider: ^5.0.0
  http: ^1.2.2
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.1
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  shared_preferences: ^2.3.3
  curved_navigation_bar: ^1.0.6
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "asset/kech.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lottie/
    - asset/
